"""Interactive onboarding. Validates your Meta token, lets you pick the ad account
and Page, collects Cloudflare R2 keys, and writes config.env. Re-runnable."""
import pathlib
from . import config as configmod, metaapi


def _ask(prompt, default='', secret=False):
    sfx = f" [{default}]" if default else ''
    val = input(f"{prompt}{sfx}: ").strip()
    return val or default


def _tmpcfg(token=''):
    c = configmod.Config()
    if token:
        c['META_ACCESS_TOKEN'] = token
    return c


TEMPLATE = """# ===== Ad Comment Intel — config =====
# (generated by `intel setup`; safe to edit by hand)

# --- Meta / Facebook ---
META_ACCESS_TOKEN={META_ACCESS_TOKEN}
META_AD_ACCOUNT_ID={META_AD_ACCOUNT_ID}
META_PAGE_ID={META_PAGE_ID}
GRAPH_VERSION={GRAPH_VERSION}

# --- Brand / pull window ---
BRAND_NAME={BRAND_NAME}
MONTHS_BACK={MONTHS_BACK}
MIN_SPEND={MIN_SPEND}
MIN_ROAS={MIN_ROAS}
TOP_BY_SPEND={TOP_BY_SPEND}
MIN_COMMENTS={MIN_COMMENTS}
MAX_PER_POST={MAX_PER_POST}

# --- Cloudflare R2 (gallery + media hosting) ---
R2_ACCOUNT_ID={R2_ACCOUNT_ID}
R2_ACCESS_KEY_ID={R2_ACCESS_KEY_ID}
R2_SECRET_ACCESS_KEY={R2_SECRET_ACCESS_KEY}
R2_BUCKET={R2_BUCKET}
R2_ENDPOINT={R2_ENDPOINT}
R2_PUBLIC_BASE={R2_PUBLIC_BASE}
"""


def main(cfg, args):
    print("=" * 60)
    print(" Ad Comment Intel — onboarding")
    print("=" * 60)
    print("This writes config.env in the current folder.\n"
          "Have ready: your Meta access token (see docs/01-create-meta-app.md)\n"
          "and your Cloudflare R2 keys (see docs/02-cloudflare-r2.md).\n")

    data = {k: cfg.get(k, '') for k in configmod.KEYS}
    data['GRAPH_VERSION'] = data.get('GRAPH_VERSION') or 'v21.0'

    # --- Meta token ---
    token = _ask("Paste your Meta access token", data.get('META_ACCESS_TOKEN', ''))
    if not token:
        print("A token is required. Aborting."); return 1
    data['META_ACCESS_TOKEN'] = token
    tc = _tmpcfg(token)

    me = metaapi.get(tc, 'me', {'fields': 'id,name'})
    if 'error' in me:
        print(f"  ! token check failed: {me['error']}")
        if _ask("Continue anyway? (y/N)", 'N').lower() != 'y':
            return 1
    else:
        print(f"  ✓ token belongs to: {me.get('name','?')} ({me.get('id','?')})")

    # --- ad account ---
    accs = metaapi.paged(tc, 'me/adaccounts', {'fields': 'name,account_id,currency,account_status', 'limit': '200'})
    if accs:
        print("\nAd accounts you can access:")
        for i, a in enumerate(accs, 1):
            print(f"  {i}. {a.get('name','?')}  (act_{a.get('account_id')}, {a.get('currency','')})")
        pick = _ask("Pick ad account #", '1')
        try:
            data['META_AD_ACCOUNT_ID'] = accs[int(pick) - 1]['account_id']
        except Exception:
            data['META_AD_ACCOUNT_ID'] = _ask("Enter ad account id (digits only)", data.get('META_AD_ACCOUNT_ID', ''))
    else:
        data['META_AD_ACCOUNT_ID'] = _ask("Enter ad account id (digits only)", data.get('META_AD_ACCOUNT_ID', ''))

    # --- page ---
    pages = metaapi.paged(tc, 'me/accounts', {'fields': 'id,name', 'limit': '200'})
    if pages:
        print("\nFacebook Pages you manage:")
        for i, p in enumerate(pages, 1):
            print(f"  {i}. {p.get('name','?')}  ({p['id']})")
        pick = _ask("Pick Page #", '1')
        try:
            data['META_PAGE_ID'] = pages[int(pick) - 1]['id']
        except Exception:
            data['META_PAGE_ID'] = _ask("Enter Page id", data.get('META_PAGE_ID', ''))
    else:
        print("  ! No Pages returned (need pages_show_list). You can paste the Page id manually.")
        data['META_PAGE_ID'] = _ask("Enter Page id", data.get('META_PAGE_ID', ''))

    # --- brand + window ---
    print()
    data['BRAND_NAME'] = _ask("Brand name (gallery title)", data.get('BRAND_NAME', '') or 'Your Brand')
    data['MONTHS_BACK'] = _ask("How many months back to analyze", data.get('MONTHS_BACK', '') or '13')
    data['MIN_SPEND'] = _ask("Min spend per post to count ($)", data.get('MIN_SPEND', '') or '300')
    data['MIN_ROAS'] = _ask("Min ROAS for 'positive ROI' cut", data.get('MIN_ROAS', '') or '1.0')
    data['TOP_BY_SPEND'] = _ask("Also always include top-N spenders", data.get('TOP_BY_SPEND', '') or '20')
    data['MIN_COMMENTS'] = data.get('MIN_COMMENTS') or '1'
    data['MAX_PER_POST'] = data.get('MAX_PER_POST') or '2000'

    # --- R2 ---
    print("\nCloudflare R2 (free) hosts the gallery + media. See docs/02-cloudflare-r2.md.")
    data['R2_ACCOUNT_ID'] = _ask("R2 account id", data.get('R2_ACCOUNT_ID', ''))
    data['R2_ACCESS_KEY_ID'] = _ask("R2 access key id", data.get('R2_ACCESS_KEY_ID', ''))
    data['R2_SECRET_ACCESS_KEY'] = _ask("R2 secret access key", data.get('R2_SECRET_ACCESS_KEY', ''))
    data['R2_BUCKET'] = _ask("R2 bucket name", data.get('R2_BUCKET', '') or 'ad-comment-intel')
    if data['R2_ACCOUNT_ID'] and not data.get('R2_ENDPOINT'):
        data['R2_ENDPOINT'] = f"https://{data['R2_ACCOUNT_ID']}.r2.cloudflarestorage.com"
    data['R2_ENDPOINT'] = _ask("R2 S3 endpoint", data.get('R2_ENDPOINT', ''))
    data['R2_PUBLIC_BASE'] = _ask("R2 public base URL (custom domain or r2.dev)", data.get('R2_PUBLIC_BASE', ''))

    # --- write ---
    out = pathlib.Path.cwd() / 'config.env'
    if out.exists():
        if _ask(f"\n{out} exists. Overwrite? (y/N)", 'N').lower() != 'y':
            print("Kept existing config. Edit it by hand if needed."); return 0
    out.write_text(TEMPLATE.format(**{k: data.get(k, '') for k in configmod.KEYS}), encoding='utf-8')
    print(f"\n✓ wrote {out}")
    print("\nNext:")
    print("  intel doctor      # verify everything connects")
    print("  intel run         # rank posts, scrape comments, publish gallery")
    return 0
